# * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# * SPDX-License-Identifier: MIT-0
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# *
---
AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation template creates a Organization conformance pack by using the conformance pack template defined in TemplateS3Uri
Parameters:
  ExcludedAccounts:
    Description: Comma delimited accounts in your organizations where you want to exclude from deploying this comformance pack
    Type: CommaDelimitedList
    Default: ''
Resources:
  TagRemediationConformancePack:
    Type: AWS::Config::OrganizationConformancePack
    Properties:
      ExcludedAccounts: !If [ ExcludedAccountsCheck, !Ref 'AWS::NoValue', !Ref ExcludedAccounts ]
      OrganizationConformancePackName: TagRemediationConformancePack
      TemplateS3Uri: <S3 URI for the comformance pack template>
Conditions:
  ExcludedAccountsCheck:
    !Equals [!Select [0, !Ref ExcludedAccounts], '']
